### ISSUE TITLE
OpenStreetMap import will break if links aren't updated before May 7

### ISSUE THREAD

**Issue by grischard** [interline-io/planetutils#3]
http://planet.openstreetmap.org is available over https, and will [start redirecting to https on 2018-05-07](https://github.com/openstreetmap/operations/issues/200).

Your project seems to be using curl, which [will not follow redirects by default](https://davidwalsh.name/curl-follow-redirects).

Would it please be possible to update all files from `http://planet.openstreetmap.org` to `httpS://planet.openstreetmap.org` before then?

Ideally, would it be possible to make all requests to openstreetmap.org over https?

**Comment by drewda** [comment]
@grischard thanks for your note. We're already defaulting to https in most cases. I've updated the one place where that apparently wasn't the case.

**Comment by drewda** [comment]
Fixed in [v0.2.5](https://github.com/interline-io/planetutils/releases/tag/v0.2.5)
